blokkr:
    resource: "@BlokkrBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#blogger_blog:
#    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
#    prefix:   /
