services:
  blokkr.service.profile:
      class: BlokkrBundle\Services\ProfileService
      arguments:
        entityRepository: "@blokkr.repository.profile"

  blokkr.repository.profile:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.default_entity_manager", getRepository]
      arguments:
        - BlokkrBundle\Entity\Profile