services:
#    blokkr.example:
#        class: BlokkrBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  app.form.registration:
      class: BlokkrBundle\Form\Authentication\UserRegisterType
      tags:
         - { name: form.type, alias: app_user_register }